// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Dug0gFiH3XpMkJqVIX9p6AeGXGpYjbs',
    appId: '1:374773879384:web:ff52c31f529e7b9fdb302d',
    messagingSenderId: '374773879384',
    projectId: 'mart-app-58fc7',
    authDomain: 'mart-app-58fc7.firebaseapp.com',
    storageBucket: 'mart-app-58fc7.appspot.com',
    measurementId: 'G-8HMHFXF6LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Nju1oZ-LBnWGYb0HgAdK7CXwQq0pP-E',
    appId: '1:374773879384:android:0341f64bcd4646f8db302d',
    messagingSenderId: '374773879384',
    projectId: 'mart-app-58fc7',
    storageBucket: 'mart-app-58fc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDduSUlA29XNKLkvJNRhJAsx123NdccF84',
    appId: '1:374773879384:ios:5745f714772886e6db302d',
    messagingSenderId: '374773879384',
    projectId: 'mart-app-58fc7',
    storageBucket: 'mart-app-58fc7.appspot.com',
    iosClientId: '374773879384-fl4l9up6i0ad3hbf7e5rnjb8e40l5afe.apps.googleusercontent.com',
    iosBundleId: 'com.example.martApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-Dug0gFiH3XpMkJqVIX9p6AeGXGpYjbs',
    appId: '1:374773879384:web:bd864b2a37e82935db302d',
    messagingSenderId: '374773879384',
    projectId: 'mart-app-58fc7',
    authDomain: 'mart-app-58fc7.firebaseapp.com',
    storageBucket: 'mart-app-58fc7.appspot.com',
    measurementId: 'G-F926YTDDJ2',
  );
}
